# xFlo
# Copyright (C) 2025 Adrien Crovato
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[project]
name = 'xflo'
description = 'eXperimental Flow - a finite volume compressible Euler flow equations solver'
version = '1.0.0'
authors = [
    { name = 'Adrien Crovato'}
]
keywords = ['Euler', 'CFD', 'aerodynamic', 'finite-volumes', 'airfoils', 'Gmsh', 'Python']
readme = 'README.md'
license = 'GPL-3.0-only'
license-files = ['LICENSE']
requires-python = '>= 3.10'
dependencies = [
    'numpy>=1.22',
    'scipy>=1.12',
    'gmsh>=4.10.5',
    'vtk>=9.6.0',
    'pytest>=9.0.2'
]

[project.scripts]
xflo-run = 'xflo.cli:main'
xflo-test = 'xflo.cli:test'

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
'xflo' = 'xflo'
'xflo._testing.tests' = 'tests'
'xflo._testing.models' = 'models'

[tool.setuptools.package-data]
'*' = ['*.dat']
